name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.1.0, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        id: tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release (Draft)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG }}
          name: Release ${{ steps.tag_name.outputs.TAG }}
          body: |
            ## 🎵 mxster Release ${{ steps.tag_name.outputs.TAG }}

            ### 📦 Downloads

            **PDF Druckkarten** (4 Karten pro A4-Seite):
            - [Standard (Farbig)](https://github.com/pepperonas/mxster/releases/download/${{ steps.tag_name.outputs.TAG }}/mxster-cards.pdf)
            - [Schwarz-Weiß](https://github.com/pepperonas/mxster/releases/download/${{ steps.tag_name.outputs.TAG }}/mxster-cards-bw.pdf)
            - [Duplex (Farbig)](https://github.com/pepperonas/mxster/releases/download/${{ steps.tag_name.outputs.TAG }}/mxster-cards-duplex.pdf)
            - [Duplex (Schwarz-Weiß)](https://github.com/pepperonas/mxster/releases/download/${{ steps.tag_name.outputs.TAG }}/mxster-cards-bw-duplex.pdf)

            **3D-Druckmodelle**:
            - [All-Cards (3MF)](https://github.com/pepperonas/mxster/releases/download/${{ steps.tag_name.outputs.TAG }}/all-cards.3mf)
            - [SCAD Models (ZIP)](https://github.com/pepperonas/mxster/releases/download/${{ steps.tag_name.outputs.TAG }}/mxster-scad-models.zip)
            - [STL Models (ZIP)](https://github.com/pepperonas/mxster/releases/download/${{ steps.tag_name.outputs.TAG }}/mxster-stl-models.zip)
            - [Einzelne Modelle im Repository](https://github.com/pepperonas/mxster/tree/main/card-generator/models)

            ### 🖨️ Druckeinstellungen
            **3D-Druck**:
            - Layer Height: 0.1-0.15mm
            - Infill: 100%
            - Material: PLA oder PETG
            - Support: Nicht nötig

            ### 📝 Assets hochladen
            Assets werden manuell hochgeladen. Nutze lokal:
            ```bash
            gh release upload ${{ steps.tag_name.outputs.TAG }} pwa/*.pdf mxster-*.zip card-generator/models/all-cards.3mf
            ```
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
